### ISSUE TITLE
Check for malformed database files before reloading clamd 

### ISSUE THREAD

**Issue by Fregf** [rseichter/fangfrisch#11]
When a malformed database is downloaded and installed by fangfrisch, the reload of the signatures in clamd will fail and clamd will exit completely, possibly breaking your mail set up:

```
Apr 28 17:29:07 hostname clamd[947]: Wed Apr 28 17:29:07 2021 -> Reading databases from /var/lib/clamav
Apr 28 17:29:36 hostname clamd[947]: LibClamAV Error: cli_parseadd(): PCRE subsig mismatched '/' delimiter
Apr 28 17:29:36 hostname clamd[947]: LibClamAV Error: Problem parsing database at line 1456
Apr 28 17:29:36 hostname clamd[947]: LibClamAV Error: Can't load /var/lib/clamav/twinclams.ldb: Malformed database
Apr 28 17:29:36 hostname clamd[947]: LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/twinclams.ldb
Apr 28 17:29:36 hostname clamd[947]: Wed Apr 28 17:29:36 2021 -> !reload db failed: Malformed database
Apr 28 17:29:38 hostname clamd[947]: Wed Apr 28 17:29:38 2021 -> Terminating because of a fatal error.
Apr 28 17:29:40 hostname systemd[1]: clamav-daemon.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 17:29:40 hostname systemd[1]: clamav-daemon.service: Failed with result 'exit-code'.

```
Before reloading the database, fangfrisch should check the database with clamscan, and if it fails, it should remove the broken files, before reloading clamd.

For example this command shows that the db is broken:
```
$ clamscan -d /var/lib/clamav/twinclams.ldb
LibClamAV Error: cli_parseadd(): PCRE subsig mismatched '/' delimiter
LibClamAV Error: Problem parsing database at line 1456
LibClamAV Error: Can't load /var/lib/clamav/twinclams.ldb: Malformed database
ERROR: Malformed database
```

**Comment by rseichter** [comment]
One can invoke a "smart" upgrade script using [on_update_execute](https://rseichter.github.io/fangfrisch/#_configuration). A typical application would be downloading signature files into a temporary directory and then running a script which validates the downloaded data. If validation passes, the new files can be moved it into a directory which is visible by ClamAV.
