### ISSUE TITLE
Option to enable specific data sources

### ISSUE THREAD

**Issue by deeztek** [rseichter/fangfrisch#16]
Is it possible to specify only the data sources you want from a feed? I see you can disable datasources but I want to specify only the data sources I want. For instance, for Sanesecurity I want to only enable the ones with Low FP score.

Thanks

**Comment by rseichter** [comment]
I see at least two ways for you to achieve what you describe:

- Copy the parts of the default Sanesecurity configuration (see [here](https://rseichter.github.io/fangfrisch/#sampleeff)) which you wish to keep into a custom data source definition and then disable the default Sanesecurity source.
- Use the `on_update_exec` configuration option to remove the data sets you don't wish to keep, for example using a small shell script.

These methods should work out of the box, without the need to modify Fangfrisch.

**Comment by deeztek** [comment]
Thanks for the quick response. I think I like the first option the best. How would I go about disabling the default sanesecurity source exactly?

Thanks

**Comment by rseichter** [comment]
Sanesecurity, like any other data source, is disabled by default. See the [documentation](https://rseichter.github.io/fangfrisch/#_configuration). You might be using a non-standard Fangfrisch configuration which enables Sanesecurity, though. It should be easy enough to spot the culprit. 😉

**Comment by rseichter** [comment]
Closing this issue because no changes to Fangfrisch are required.
