### ISSUE TITLE
Possible to use environment variables for db_url?

### ISSUE THREAD

**Issue by nishils** [rseichter/fangfrisch#25]
Hi there,

Is there was a simple way to pass the db_url connection string via an environment variable? Right now, our database isn't located on the same machine as fangfrisch so we have password protection enabled for the database user. The issue is that it seems like db_url in the configuration file requires a hardcoded string that would include the database password being written to disk.

Would it be possible to just read the default db_url to also read from FANGFRISCH_DB_URL or more generally, allow us to configure which environment variable the any configuration should be read from?

I dug through the source code and all the issues but didn't anything about environment variables generally being supported.

Thanks for the help!

**Comment by rseichter** [comment]
Fangfrisch itself does not currently support using environment variables to configure database connections. I also don't think it would be a good idea to hold password data in the process environment anyway, if you are concerned with security. The Fangfrisch configuration file need only be readable by the particular, non-privileged user account you chose for running the Python process, so `db_url` is not inherently unsafe. All that said: Fangfrisch uses SQLAlchemy to handle database connections, and perhaps SQLAlchemy supports environment variables? I don't know if it does, but perhaps you'd like to investigate for yourself?

**Comment by nishils** [comment]
Thanks for the response! I'll go ahead and close this out as it seems out of scope.

> I also don't think it would be a good idea to hold password data in the process environment anyway, if you are concerned with security.

Fair but the current situation is to hardcode the password in the config file which is definitely worse by writing to disk.

> The Fangfrisch configuration file need only be readable by the particular, non-privileged user account you chose for running the Python process, so db_url is not inherently unsafe.

That's a fair point.

> All that said: Fangfrisch uses SQLAlchemy to handle database connections, and perhaps SQLAlchemy supports environment variables? I don't know if it does, but perhaps you'd like to investigate for yourself?

Yes looked into SQLAlchemy 1.4 pretty heavily but no solution there unfortunately. Usually some people pass the os.environ into the ConfigParser to allow for this.

However with that all that said, I rediscovered the `envsubst` bash utility which allows for templating the config file so might try that out.

**Comment by rseichter** [comment]
> the current situation is to hardcode the password in the config file which is definitely worse by writing to disk.

I think it is easier to control access to a file than to environment memory, which by the way may also be swapped out to disk, or included in memory dumps. Also, a locally stored SQLite DB is completely sufficient. Fangfrisch only stores minimal data about which signature files were downloaded and when that last happened. There is no tangible advantage gained by using a remote database, and it adds unnecessary complexity.

> I rediscovered the `envsubst` bash utility which allows for templating the config file so might try that out.

I often rely on Ansible to roll out software, using templates for configuration files. Sensitive data can then be pulled from an encrypted Ansible vault. Docker secrets are also an option, if one is using containers. Still, I recommend SQLite for Fangfrisch, a remote DB really is overkill.

**Comment by nishils** [comment]
>I think it is easier to control access to a file than to environment memory, which by the way may also be swapped out to disk, or included in memory dumps. Also, a locally stored SQLite DB is completely sufficient. Fangfrisch only stores minimal data about which signature files were downloaded and when that last happened. There is no tangible advantage gained by using a remote database, and it adds unnecessary complexity.

We actually use kubernetes with docker containers so the compute instances may disappear at any time and we want to make sure we stick to the rate limits as the instances can be constantly swapped around. Though in practice they are somewhat stable. A remote postgres database is fairly easy to spin up and fairly cheap. So I agree in most setups this would be overkill, but in our environment, it is actually fairly simple.

 >I often rely on Ansible to roll out software, using templates for configuration files. Sensitive data can then be pulled from an encrypted Ansible vault. Docker secrets are also an option, if one is using containers. Still, I recommend SQLite for Fangfrisch, a remote DB really is overkill.

Yes, we have a way to grab secrets so there's not much optionality to change this, but the `envsubst` command can work for us.

**Comment by rseichter** [comment]
It is good to hear that you figured out a method which works for you. Out of sheer curiosity: I don't suppose you use a single shared database instance for multiple Fangfrisch instances, or do you? That would not fit my design, and I would expect a shared setup to fail.
