### ISSUE TITLE
error when initdb on an existing database

### ISSUE THREAD

**Issue by happysalada** [rseichter/fangfrisch#26]
hey, first of all thank you for this software!

I wanted to ask why it is that running initdb on an existing database gives an error ?

The reason it is a bit surprising is that in order to make a systemd service for this, you have to make an "init" oneshot service that will run once to init the db. However if you ever disable and re-enable the service, the init will fail.
To that reason I'm making an init service on nixos that initdb with --force (to make sure it never errors out, that way you can enable and disable fangfrisch at will).
I just wanted to know if there were any considerations I missed.

Thank you again for this!

**Comment by rseichter** [comment]
I wanted to ensure that users don't accidentally lose their database contents. Also, Fangfrisch uses SQLAlchemy as a database abstraction layer, and should this library change its initialisation behaviour in future versions, it might result in Fangfrisch behaving differently for different users, depending on their respective versions of SQLAlchemy. Hence, I introduced the ˋ--forceˋ option, which I do not recommend using in automated/scripted settings like a systemd unit file.

**Comment by happysalada** [comment]
Thank you for your feedback. What is the expected value ?

**Comment by rseichter** [comment]
For my own setup, the following shell commands return the answer you are looking for. 😉

```
echo "select db_version from automx2;" | sqlite3 /var/lib/fangfrisch/db.sqlite
```

The actual value may change in the future, if I ever need to make changes to the database structure.

**Comment by happysalada** [comment]
Alright im going to take a shortcut now and allow failure of the init process. Rather than depending on a value that may change in the future.
Ive just added this option to nixos so most users will be first time users.
If someone posts an issue about an error on init ill link to this issue.

Thanks a lot for your quick response on this !

(I hope you dont mind me taking a shortcut here)

**Comment by rseichter** [comment]
I don't mind. In fact, I am glad whenever a Linux distribution maintainer takes the time to ask me about specifics or possible pitfalls.

A simple method for SQLite would be: Does the database file exist? If so, assume that initdb has been already run, and if not, run initdb (which will also create the DB file itself). For other databases like PostgreSQL or MariaDB, one can use `automx2.db_version` as I mentioned. How it is best done for a particular distribution XYZ is something maintainers such as yourself know more about than I do (unless XYZ happens to be Gentoo Linux, which I use myself in most cases).

I am sure that you will pick a suitable solution.

**Comment by happysalada** [comment]
Actually that is a much better solution. Thank you !
