### ISSUE TITLE
Timeout Sanesecurity from AS3320

### ISSUE THREAD

**Issue by bsdice** [rseichter/fangfrisch#27]
Yo,

I'm seeing alot of these when updating Sanesecurity:

    ERROR: HTTPConnectionPool(host='ftp.swin.edu.au', port=80): Read timed out. (read timeout=30)

I tested with a browser and it is slow as molasses, coming from Deutsche Telekom AS3320. It works, but is really slow. I checked traceroute for IPv6 and that looks very nasty. Problem has persisted for months I just ignored it so far.

I fixed it temporarily by hot-modifying timeout=30 here: https://github.com/rseichter/fangfrisch/blob/master/fangfrisch/download.py#L57 I set it to 120 seconds and the error is gone.

Any chance to make this configurable? Or some other option?

(Edit: And bump version number so Arch picks it up...)

Thanks, Stephan

**Comment by rseichter** [comment]
I'll need to look into how to handle timeouts in a more flexible manner. The current value of 30 seconds is already pretty high, a grudgingly made compromise based on measurements I took during development. A hard coded increase is not a good idea, that could completely break scheduling.

**Comment by rseichter** [comment]
Superseded by issue #29
