### ISSUE TITLE
Tests infeasible to run for downstreams

### ISSUE THREAD

**Issue by kitterma** [rseichter/fangfrisch#34]
I was looking into enabling the frangfrisch test suite to run during package build and in the Debian CI infrastructure, but quickly ran into issues.

1.  During package build, there is no internet access (to make sure that the Debian archive is self-contained).  As a result, any tests that require internet access to run, will fail.  This is not a huge issue as it's common that really testing things requires doing something on a network and mocking the required network connections is non-trivial.

2.  In our CI environment, tests are run periodically, so multiple connects from a single host are normal.  Low thresholds for blocking access make running the tests in CI unreliable.

In the course of trying to enable the tests, I quickly started getting errors like:

`requests.exceptions.ProxyError: HTTPSConnectionPool(host='seichter.de', port=443): Max retries exceeded with url: /favicon-16x16.png (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d1992a690>: Failed to establish a new connection: [Errno 111] Connection refused')))`

I don't know what would be the best solution to this, but currently, for Debian, running these tests is not feasible.

Scott K

**Comment by rseichter** [comment]
For my [automx2](https://github.com/rseichter/automx2) project, I use an environment variable to enable/disable tests which require a network connection to my LDAP server. I think I will make similar modifications to Fangfrisch's tests.

**Comment by rseichter** [comment]
I made [the changes](https://github.com/rseichter/fangfrisch/blob/network-tests/CHANGELOG.rst) in branch "network-tests".  Things work as expected in GitHub CI. Perhaps you'd be willing to give it a try?

**Comment by kitterma** [comment]
On February 21, 2024 2:03:51 PM UTC, Ralph Seichter ***@***.***> wrote:
>Closed #34 as completed via 17aafcc76936fc7e122f23a86896e07f00badf56.
>

Thanks.  It'll be a few days probably before I can get to it, but I will definitely give it a try.

Scott K

**Comment by rseichter** [comment]
@kitterma It was a simple change, and it does not really need special testing on your end. The modifications are included in [release 1.8.1](https://github.com/rseichter/fangfrisch/releases/tag/1.8.1), so if you were to package that... 😉

**Comment by kitterma** [comment]
Done.  You can see the test run in the build log:

https://buildd.debian.org/status/fetch.php?pkg=fangfrisch&arch=all&ver=1.8.1-1&stamp=1708702489&raw=0

Scott K

**Comment by rseichter** [comment]
@kitterma That's one impressive looking log. Thanks for packaging this release for Debian. I have submitted a pull request for a matching Gentoo ebuild, and I have also created an Arch Linux AUR package for Fangfrisch 1.8.1. Having network-based tests disabled by default really makes packaging easier; thank you for suggesting this.

**Comment by kitterma** [comment]
On February 23, 2024 6:25:26 PM UTC, Ralph Seichter ***@***.***> wrote:
>@kitterma That's one impressive looking log. Thanks for packaging this release for Debian. I have submitted a pull request for a matching Gentoo ebuild, and I have also created an Arch Linux AUR package for Fangfrisch 1.8.1. Having network-based tests disabled by default really makes packaging easier; thank you for suggesting this.
>

Tests are also being run periodically and when any dependency is updated on the Debian CI infrastructure:

https://ci.debian.net/packages/f/fangfrisch/

Scott K
