### ISSUE TITLE
Use yes/no or true/false for enabled

### ISSUE THREAD

**Issue by chkpnt** [rseichter/fangfrisch#41]
Currently, the docs use `yes/false` for the enabled option. Of cource, this is [valid](https://docs.python.org/3/library/configparser.html#supported-datatypes), but using one of the usual pairs `yes/no` or `true/false` is less surprising.

**Comment by rseichter** [comment]
Oops, that's an oversight on my end. Thank you for reporting this issue.

**Comment by rseichter** [comment]
Fixed in commit e3cfcc61d9bd7aeeee3f6d6c5da9cab164d2b648. All it took was a single change in the Configuration base class.
