### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by Massimo-B** [rseichter/fangfrisch#42]
fangfrisch-1.9.0

Please provide an option to locally configure a specific proxy server for fangfrisch passing to the requests library, if a global HTTPS_PROXY in the environment is not an option.

**Comment by rseichter** [comment]
I want to be certain that I understand what you wrote. Are you saying that the requests library does not support the HTTPS_PROXY environment variable (it does, according to the library documentation), or are you saying that you launch Fangfrisch in a particularly unusual way which prevents you from setting the variable? If the latter is what you mean, please explain in detail how you run Fangfrisch.

**Comment by chkpnt** [comment]
In case you are using a systemd timer to start fangfrisch, you can set the proxy variables in your unit file, e. g.

<pre>
[Unit]
Description=Fangfrisch updater for Clam Anti-Virus signatures
After=network-online.target nss-lookup.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/fangfrisch --conf /etc/fangfrisch.conf refresh
User=vscan
Group=vscan
<b>Environment="HTTP_PROXY=http://proxy.example.com:8080"</b>
<b>Environment="HTTPS_PROXY=http://proxy.example.com:8080"</b>
# If no_proxy is needed to bypass proxy for specific addresses
<b>Environment="NO_PROXY=localhost,127.0.0.1"</b>
</pre>

**Comment by Massimo-B** [comment]
Ok, systemd would have a way to pass service environments... I'm not using systemd but OpenRC.

Current workaround is passing it to the sudo or inside the cronjob like this:

`sudo -u clamav http_proxy="http://foo:8080" fangfrisch -c /etc/fangfrisch.conf refresh`

I know HTTPS_PROXY is supported. But I like to set it for fangfrisch only, not globally. Or I like to use a different proxy there. For now, the workaround is sufficient for me..

**Comment by rseichter** [comment]
@Massimo-B Specifying environment variables using `VARNAME=value /path/to/command` is not really a workaround, as you called it, but a typical way of doing things. In OpenRC, you can also use this method, or as an alternative set up the desired environment before a particular service is started:

```
start_pre() {
    export HTTPS_PROXY="..."
}
```

You may want to check the contents of `/etc/init.d` for additional inspiration.
