### ISSUE TITLE
log_method syslog not working with metalog

### ISSUE THREAD

**Issue by Massimo-B** [rseichter/fangfrisch#44]
Coming from https://github.com/hvisage/metalog/issues/32 ...

Setting log_method to syslog doesn't log anything to metalog:
```
# grep log /etc/fangfrisch.conf 
log_level = DEBUG
log_method = syslog
```

Removing the log_method and falling back to "console", the logging to STDOUT works as expected.

Gentoo Linux 23.0
app-antivirus/fangfrisch-1.9.0
app-antivirus/clamav-1.2.2
dev-lang/python-3.12.3-r1
app-admin/metalog-20230719

**Comment by rseichter** [comment]
Quoting from my own `fangfrisch.conf` (production server):
```
[DEFAULT]
log_level = DEBUG
log_method = syslog
log_target = /dev/log
```
This works as expected, in this specific case in combination with syslog-ng version 4.6.0. I have never used Metalog myself.

**Comment by rseichter** [comment]
By the way: The description "doesn't log anything to metalog" is not enough to go on, unsurprisingly. You may already have guessed that, but I wanted to be clear that I won't be able to investigate based on what little information you have provided so far.

**Comment by rseichter** [comment]
Let's stick with the original metalog [issue](https://github.com/hvisage/metalog/issues/32) for the time being. No need to keep two separate tickets open.
