### ISSUE TITLE
it would be great...

### ISSUE THREAD

**Issue by feanorknd** [rseichter/fangfrisch#48]
Hi there!!

thanks so much for your script.. so useful!

It would be great if it could just autodetect downloaded file and, for example, if it is a zip file, just decompress and place...

For example, I am using:

[yaraforge]
enabled = yes
interval = 1d
url_yarahub = https://github.com/YARAHQ/yara-forge/releases/latest/download/yara-forge-rules-full.zip
integrity_check = disabled
on_update_yaraforge = unzip -qq -j -o -d /var/lib/clamav {path}

and it is nice, but stored zip file will be kept there... even cannot do something like:
"unzip -qq -j -o -d /var/lib/clamav {path} && rm -f {path}"
(as it fails)

Have seen interesting repos but yar files are stored inside zips..

Thanks!

**Comment by rseichter** [comment]
For the scenario you describe, I suggest something along these lines:

```
# Custom unzip.sh wrapper script
unzip -qq -j -o -d /var/lib/clamav "$1" && rm "$1"
```

Combined with `on_update_yaraforge = bash /path/to/unzip.sh {path}` this should cover your needs.

**Comment by rseichter** [comment]
I'm closing this issue, because automatic archive extraction seems like a niche use case to me.
