### ISSUE TITLE
Python 3.6 optional?

### ISSUE THREAD

**Issue by robbat2** [rseichter/fangfrisch#5]
The dependencies declared in the setup state Python 3.7, but I'm wondering if you could relax it slightly to accept Python 3.6 as well, to make upgrade processes easier where Python 3.7 isn't always available yet in the system python.

**Comment by rseichter** [comment]
Fangfrisch uses a feature introduced with Python 3.7, meaning the code won't execute with earlier versions. Python 3.7 was released as production-stable in [June 2018](https://www.python.org/dev/peps/pep-0537/), and I am unaware of operating systems that do not provide Python 3.7 as of today (May 2020). If you come across one, I encourage you to ask the OS/distribution maintainers to work towards improving their Python support.
