### ISSUE TITLE
Config File Location

### ISSUE THREAD

**Issue by trev-dev** [rseichter/fangfrisch#6]
Hey this may seem like an obvious thing to most other people but I can't seem to figure out where to create a config file and what to call it. Any advice?

**Comment by rseichter** [comment]
Fangfrisch makes no assumptions about name or location, because that usually depends on the OS. Personally, I prefer `fangfrisch --conf /etc/fangfrisch.conf` on Gentoo Linux. You are however free to choose your poison.

**Comment by rseichter** [comment]
I have updated [the documentation](https://rseichter.github.io/fangfrisch/#_configuration) to clarify that there is no default configuration file location.
