### ISSUE TITLE
Option to disable single data source from provider

### ISSUE THREAD

**Issue by Fregf** [rseichter/fangfrisch#8]
The sanesecurity provider downloads scanmnailer.ndb. However this is unmaintained and its author discourages its use:
http://www.scamnailer.info/

I would like to disable this source on my installation, without disabling the complete sanesecurity provider. I could create a custom sanesecurity provider without the scanmailer source, but an easier way would be helpful.

**Comment by rseichter** [comment]
Thanks for the notice. Looks like I should remove the URL from the default configuration.

Until a new release becomes available, the following should work:
```
[sanesecurity]
filename_scamnailer = /dev/null
```
Remember to manually remove the previously downloaded `/var/lib/clamav/scamnailer.ndb`.

**Comment by rseichter** [comment]
I have made a [developer pre-release](https://pypi.org/project/fangfrisch/1.2.1.dev2/) available. This version disables scamnailer.ndb by default.
